version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - touch ./web/.env
      - printenv > ./web/.env
      - cat ./web/.env
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker-compose build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker-compose push
      - echo Writing image definitions file...
      - sed -i'' -e "s/%AWS_DEFAULT_REGION%/${AWS_DEFAULT_REGION}/g" Dockerrun.aws.json
      - sed -i'' -e "s/%AWS_ACCOUNT_ID%/${AWS_ACCOUNT_ID}/g" Dockerrun.aws.json
artifacts:
  files:
    - Dockerrun.aws.json