version: '3.7'

services:
#      "command": ["gunicorn","CalculatorAPP.wsgi:application","--bind",":8000","--timeout ","1800"],
#             "command": ["celery","-A","CalculatorAPP","worker","-l ","info"],
 database:
  build:
   context: ./database
  hostname: database
  image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dev-database
  environment:
   - POSTGRES_HOST=database
   - POSTGRES_DB=dbname
   - POSTGRES_USER=dbuser
   - POSTGRES_PASSWORD=pass
   - POSTGRES_PORT=5432
  ports:
   - "5400:5432"

 redis:
  build:
   context: ./redis
  hostname: redis
  image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dev-redis
  expose:
   - 6379

 dev-app:
  build:
   context: .
  hostname: dev-app
  image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dev-app
  env_file:
   - ./web/.envfile
  expose:
   - 8000
  depends_on:
   - database
   - redis

 nginx:
   build:
    context: .
    dockerfile: ./nginx/Dockerfile
   hostname: nginx
   image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dev-nginx
   ports:
      - '80:80'
   depends_on:
    - dev-app

 worker:
  build:
   context: .
   dockerfile: ./worker/Dockerfile
  hostname: worker
  image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dev-worker
  env_file:
   - ./web/.envfile
  links:
   - redis
  depends_on:
   - redis
   - dev-app
   - database