version: '3.7'
services:

 database:
  build:
   context: ./database
  hostname: database
  environment:
   - POSTGRES_HOST=database
   - POSTGRES_DB=dbname
   - POSTGRES_USER=dbuser
   - POSTGRES_PASSWORD=pass
   - POSTGRES_PORT=5432
  ports:
   - "5400:5432"

 redis:
  build:
   context: ./redis
  hostname: redis
  expose:
   - 6379

 dev-app:
  build:
   context: .
  hostname: dev-app
  env_file:
   - ./web/.env
  expose:
   - 8000
  depends_on:
   - database
   - redis

 nginx:
   build:
    context: .
    dockerfile: ./nginx/Dockerfile
   hostname: nginx
   ports:
      - '8000:80'
   depends_on:
    - dev-app

 worker:
  build:
   context: .
   dockerfile: ./worker/Dockerfile
  env_file:
   - ./web/.env
  links:
   - redis
  depends_on:
   - redis
   - dev-app
   - database

