version: '3.7'
services:

 database:
  build:
   context: ./database
  image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dev-database
  environment:
   - POSTGRES_DB=dbname
   - POSTGRES_USER=dbuser
   - POSTGRES_PASSWORD=pass

 redis:
  build:
   context: ./redis
  image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dev-redis

 dev-app:
  build:
   context: .
  image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dev-app

 nginx:
   build:
    context: .
    dockerfile: ./nginx/Dockerfile
   image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dev-nginx
   restart: always
   ports:
      - '80:80'
   volumes:
     - ./web/static:/home/app/web/static

 worker:
  build:
   context: .
  image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dev-worker

