version: '3.7'
services:

 database:
  build:
   context: ./database
  image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dev-database
  container_name: database
  restart: unless-stopped
  environment:
   - POSTGRES_DB=dbname
   - POSTGRES_USER=dbuser
   - POSTGRES_PASSWORD=pass

 redis:
  build:
   context: ./redis
  image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dev-redis
  restart: unless-stopped
  container_name: redis
  expose:
   - 6379

 dev-app:
  build:
   context: .
  restart: unless-stopped
  container_name: dev-app
  image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dev-app
  expose:
   - 8000
  command: >
   sh -c "python manage.py makemigrations
   && python manage.py migrate
   && python manage.py collectstatic --noinput
   && python manage.py createsuperuser_if_none_exists
   && gunicorn CalculatorAPP.wsgi:application --bind :8000 --timeout 1800"
  depends_on:
   - database
   - redis

 nginx:
   build:
    context: ./nginx
   container_name: nginx
   image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dev-nginx
   restart: unless-stopped
   ports:
      - '80:80'
   volumes:
     - ./web/static:/home/app/web/static
   depends_on:
     - dev-app

 worker:
  build:
   context: .
  container_name: worker
  restart: unless-stopped
  image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/dev-worker
  command: celery -A CalculatorAPP worker -l info
  links:
   - redis
  depends_on:
   - redis
   - dev-app
   - database
