# Generated by Django 4.1.6 on 2023-05-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposurehistory',
            name='year_from',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='exposurehistory',
            name='year_to',
            field=models.CharField(max_length=20),
        ),
    ]
