# Generated by Django 4.1.6 on 2023-05-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipsShipyards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shipyard',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
